name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Run Makefile
        run: |
          make all
